version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
      - .env.test
    environment:
      - NODE_ENV=development